### ISSUE TITLE
[Feature] Electron IPC messages capturing and presenting

### ISSUE THREAD

**Issue by tyn1998** [opensumi/devtools#1]
### 初步调查

假设我是一个opensumi/core的集成方，如果要做electron应用，那么一定会使用到@opensumi/ide-core-electron-main模块。于是，如果ipc捕获功能需要opensumi/core配合的话，我就应该着眼于修改ide-core-electron-main模块。

ide-electron项目是一个示范项目，指导集成方如何基于opensumi/core打造electron应用。

opensumi/core的tools/electron类似于ide-electron，但是更加简单一点。

@yantze老师，请问我的上面3个理解对吗？

**Comment by tyn1998** [comment]
查看代码时的想到的问题：

https://github.com/opensumi/core/blob/main/packages/core-common/src/mocks/electron/ipcRenderer.ts

@yantze 老师，请问这个MockedElectronIpcRenderer是做什么用的？只是为了测试用吗？

**Comment by tyn1998** [comment]
马克一下：

https://github.com/opensumi/core/pull/1560 中，在core-browser/src/bootstrap/app.ts的构造函数中向`window`全局变量插上HOOK。

如果是electron app的形式，那么会先启动electron的main thread，main thread[再启动](https://github.com/opensumi/core/blob/052a035146f3e4b39ae4d3aae332cec012cafe4e/packages/core-electron-main/src/bootstrap/window.ts#L192)browser window，所以这里有个**时间先后关系，要留心一下**。

**Comment by tyn1998** [comment]
### 外挂式和侵入式的选择

Devtron的[做法](https://github.com/electron-userland/devtron/blob/c2d06028bb75c5cc5567b272a866e6d6e75223df/lib/ipc-helpers.js#L43-L66)是在loadExtension的时候（应该是比较初始的时间点），就对ipcRenderer的方法做个代理，这样后面用到ipcRenderer的各个方法时，被改造过的方法都会把消息给捕捉了。

`browserNodeIntegrated`是集成方控制的一个配置项，如ide-connection[设置为true](https://github.com/opensumi/ide-electron/blob/88ea1b474f774ca0ad882e9ec15fad419daf7763/src/main/launch.ts#L51)，但是core中的electron是设置为false的。

若`browserNodeIntegrated`为`true`，那么opensumi-devtools可以像Devtron那样，直接`require('electron').ipcRenderer`和~require('electron').ipcMain~来改造，是完全外挂式的。但是，若`browserNodeIntegrated`为`false`，那么opensumi-devtools中无法访问模块，只能采用捕获ws messages那样的方法，即需要opensumi/core进行配合。

我个人更倾向于侵入式的方式，@yantze老师怎么看？

**Comment by tyn1998** [comment]
与Electron IPC相关的API一共有多少？

[官网](https://www.electronjs.org/docs/latest/tutorial/ipc)介绍的有若干个；electron.d.ts中还有其他官网没提到的。

只处理官网介绍的那几个API是否足够？@yantze

**Comment by yantze** [comment]
> ### 初步调查
> 假设我是一个opensumi/core的集成方，如果要做electron应用，那么一定会使用到@opensumi/ide-core-electron-main模块。于是，如果ipc捕获功能需要opensumi/core配合的话，我就应该着眼于修改ide-core-electron-main模块。
> 
> ide-electron项目是一个示范项目，指导集成方如何基于opensumi/core打造electron应用。
> 
> opensumi/core的tools/electron类似于ide-electron，但是更加简单一点。
> 
> @yantze老师，请问我的上面3个理解对吗？

对的，如果有相关的修改，最好是 ide-core-electron-main

**Comment by yantze** [comment]
> 查看代码时的想到的问题：
> 
> https://github.com/opensumi/core/blob/main/packages/core-common/src/mocks/electron/ipcRenderer.ts
> 
> @yantze 老师，请问这个MockedElectronIpcRenderer是做什么用的？只是为了测试用吗？

对的

**Comment by yantze** [comment]
> ### 外挂式和侵入式的选择
> Devtron的[做法](https://github.com/electron-userland/devtron/blob/c2d06028bb75c5cc5567b272a866e6d6e75223df/lib/ipc-helpers.js#L43-L66)是在loadExtension的时候（应该是比较初始的时间点），就对ipcRenderer的方法做个代理，这样后面用到ipcRenderer的各个方法时，被改造过的方法都会把消息给捕捉了。
> 
> `browserNodeIntegrated`是集成方控制的一个配置项，如ide-connection[设置为true](https://github.com/opensumi/ide-electron/blob/88ea1b474f774ca0ad882e9ec15fad419daf7763/src/main/launch.ts#L51)，但是core中的electron是设置为false的。
> 
> 若`browserNodeIntegrated`为`true`，那么opensumi-devtools可以像Devtron那样，直接`require('electron').ipcRenderer`和`require('electron').ipcMain`来改造，是完全外挂式的。但是，若`browserNodeIntegrated`为`false`，那么opensumi-devtools中无法访问模块，只能采用捕获ws messages那样的方法，即需要opensumi/core进行配合。
> 
> 我个人更倾向于侵入式的方式，@yantze老师怎么看？

外挂的方式应该也可以， devtools 自身其实也是一个 renderer，你可以直接获取到 devtools 的窗口 id，然后 main 进程发送给  devtools

**Comment by yantze** [comment]
> 与Electron IPC相关的API一共有多少？
> 
> [官网](https://www.electronjs.org/docs/latest/tutorial/ipc)介绍的有若干个；electron.d.ts中还有其他官网没提到的。
> 
> 只处理官网介绍的那几个API是否足够？@yantze

其它的暂时应该用不到的

**Comment by tyn1998** [comment]
UI设计上，我打算这么做：

![image](https://user-images.githubusercontent.com/32434520/186610849-7dcf15fd-9ab8-44c2-9771-5aa252f3e54a.png)

将目前的toolbar往右移动一点，左边腾出来加一个新按钮“RPC/IPC”用于切换两种消息列表。RPC目前的toolbar以蓝色为主，IPC的toolbar可以以橙色为主，这样容易区别。

另外，切换RPC/IPC不会重新渲染，也就是说当从RPC切到IPC，再切回RPC，RPC的内容在期间是一直“持续”着的，不会清零。

还有一点，IPC messages是Electron特有的，因此要在ide-core-electron-main暴露出一个标志，让devtools识别到。这样，如果检测到是Electron端，则在RPC视图的基础上，会加上IPC视图。

**Comment by tyn1998** [comment]
> 外挂的方式应该也可以， devtools 自身其实也是一个 renderer，你可以直接获取到 devtools 的窗口 id，然后 main 进程发送给 devtools

@yantze 老师，这个能不能更具体点点？我还打算和RPC的捕获方式保持一致呢，就是用`window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK.ipcMessages`做中介。

**Comment by yantze** [comment]
> > 外挂的方式应该也可以， devtools 自身其实也是一个 renderer，你可以直接获取到 devtools 的窗口 id，然后 main 进程发送给 devtools
> 
> @yantze 老师，这个能不能更具体点点？我还打算和RPC的捕获方式保持一致呢，就是用`window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK.ipcMessages`做中介。

保持一致也可以，那就不需要 devtools 的窗口 id

**Comment by tyn1998** [comment]
OK，先用类似的方法来做。以后有更好的方法可以重构~

**Comment by tyn1998** [comment]
### 外挂式不大行

> 先解释一下我说的“外挂式”和“侵入式”是指什么。“外挂式”是指基本不需要动opensumi/core的代码，只要在devtools里写代码就能达到目的的方式；“侵入式”指必须要改opensumi/core的代码才能达到目的的方式。

经过一番摸索，我认为外挂式不行，理由如下：

1. 外挂式需要Electron开启`browserNodeIntegrated`，而开启此选项被认为是有安全风险的，一般不推荐开启
2. 即使该选项开启了，在browser中`require('electron').ipcMain`得到undefined，只有ipcRenderer是能够access的。这意味着在外挂式的条件下，devtools只能改造ipcRenderer而不能改造ipcMain。事实上，DevTron改造的就只有ipcRenderer。

### 侵入式的摸索

比如说要改造`ipcMain.on`这个方法。

首先，这个改造时间点要尽早，要在所有用到`ipcMain.on`的时间之前。此外，要运行在main进程的范围中。因此，我挑选core-electron-main/src/bootstrap/app.ts的import语句后的位置。

对于on类的方法，不像send类每次有消息要发送都会执行一次，on类只会在注册的时候执行一次，因此要考虑代理参数中的handler，我是这么做的：

```javascript
const originalOn = ipcMain.on;
ipcMain.on = function (channel: any, handler: any) {
  const proxyHandler = (event: any, ...args: any) => {
    capture(channel, event, args); // 还没写，应该会和rpc那里的capture类似的处理
    handler(event, ...args);
  };
  return originalOn.call(ipcMain, channel, proxyHandler);
};
```

上面这个方法是可以成功的，我在测试的时候还加了几句`console.log`，可以在本地shell中看到。

对于其他`ipcMain.xxx`和`ipcRenderer.xxx`，我打算在core-electron-main合适的位置中改造。@Yantze老师觉得这样可以吗？

**Comment by tyn1998** [comment]
> 2\. devtools只能改造ipcRenderer而不能改造ipcMain

类比到rpc的前端和后端，我突然发现ipcMain就是Electron app的后端。rpc的后端我们是不捕获的，那么Electron app的后端也不用捕获吗？

**Comment by yantze** [comment]
先用侵入式这种方式，提供原始数据吧，这种不确定会不会对性能产生影响，如果有明显的影响，可能需要后面添加开关实现。

**Comment by yantze** [comment]
> > 2. devtools只能改造ipcRenderer而不能改造ipcMain
> 
> 类比到rpc的前端和后端，我突然发现ipcMain就是Electron app的后端。rpc的后端我们是不捕获的，那么Electron app的后端也不用捕获吗？

main 进程是广播式，所以监听 main 进程的消息是有必要的，不过可以放到后面做也行

**Comment by tyn1998** [comment]
ok

**Comment by tyn1998** [comment]
> 外挂的方式应该也可以， devtools 自身其实也是一个 renderer，你可以直接获取到 devtools 的窗口 id，然后 main 进程发送给 devtools

> 保持一致也可以，那就不需要 devtools 的窗口 id

Too young too naive，我天真的想着从main进程里用`window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__.captureIpc`把消息放到`window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__.ipcMessages`中，完全忽略了main进程里面根本没有`window`。

所以就像@Yantze老师给的建议那样，涉及到ipcMain的消息捕获本身就需要利用IPC通信才能间接/直接传给devtools。

至于是main -> browser -> devtools还是main -> devtools，我得摸索后才能确定。

**Comment by tyn1998** [comment]
@yantze 老师，opensumi devtools要判断是在Web还是Electron中打开。刚才我是在core-browser/src/bootstrap/app.ts中加了一段：

<img width="812" alt="image" src="https://user-images.githubusercontent.com/32434520/186831784-3da5a5b1-d3dc-47ed-9e22-e772c5dd02ef.png">

但现在我发现core-electron-main/browser-preload/index.js中已经有`electronEnv`暴露给`global`也就是window对象了，您觉得用哪个好？

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/32434520/186832093-666a3d3c-46bf-4d4e-81ad-ab7c3d85a1e4.png">

**Comment by yantze** [comment]
用 electronEnv 就行了，避免过多的 DevTools 的逻辑

**Comment by tyn1998** [comment]
opensumi/core对捕获IPC消息的支持刚刚提了个[Draft PR](https://github.com/opensumi/core/pull/1583)。

devtools这边，IPC消息列表的columns我打算这么设计：

- ID
- Time
- IPC Method
- Channel
- Arguments

如果Arguments普遍不复杂的话，~也许可以不用JSON View~(还是要用，后来发现一个长的，设置菜单的那个)，而是像DevTron这样直接当一个普通单元格：

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/32434520/186896877-97f7c501-d2cd-47f8-a760-53b5099ce50b.png">

另外，@yantze 老师，怎么能多触发一些Electron IPC API，像`ipcRenderer.send`这种，我粗粗看了下，代码里用到的很少，都不好测试:joy:。亲测通过UI可以触发的有：缩放移动窗口，点击菜单栏中的选项。
