### ISSUE TITLE
[CD] release for v1.2.1 failed (in upload phase)

### ISSUE THREAD

**Issue by tyn1998** [opensumi/devtools#18]
Refer to: https://github.com/opensumi/devtools/actions/runs/4666093085/jobs/8260258533

不知道什么原因，release版本后，到了上传zip到商店这个step出错了。于是访问管理平台手动上传了最新的zip包，目前等待审核，审核通过后就会自动发布：

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/32434520/231121773-3865996f-cc3a-4b0e-a0f1-108fa3630396.png">

**Comment by bytemain** [comment]
![CleanShot 2024-04-22 at 14 28 53@2x](https://github.com/opensumi/devtools/assets/13938334/0b9b73ca-41d5-4e06-b6ea-3156f00e1f7c)

问题还是存在
