### ISSUE TITLE
[Discussion] deploy to chrome webstore

### ISSUE THREAD

**Issue by tyn1998** [opensumi/devtools#2]
### 发布到商店的好处

目前的安装方式除了略微繁琐外，最大的问题是不能自动更新，每次如果有新版本，就要手动下载更新。

如果将OpenSumi DevTools发布到chrome的webstore中，那么：

- 对于web，可以直接在浏览器中安装插件
- 对于Electron，可以利用[electron-devtools-installer](https://www.npmjs.com/package/electron-devtools-installer)进行安装，只要给出插件在商店中的ID，electron-devtools-installer就会自动下载安装到Electron中。

### 发布到商店前的准备

- 注册谷歌开发者账号（需要visa卡支付一点开通费💰）

### 发布到商店后

- 根据[this guide](https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md)获取一些token存到仓库的secrets中，用于[自动发布](https://github.com/fregante/chrome-webstore-upload/)

@erha19 @yantze ，请问老师们近期会有发布到webstroe的安排吗？

**Comment by erha19** [comment]
@tyn1998 先内测使用一段时间，后面跟 @iamxukai 做的快捷键插件一起发 Chrome 插件市场吧，费用这块不用担心，另外前期可以准备把自动化流程部署一下 https://github.com/marketplace/actions/chrome-extension-upload-publish

**Comment by tyn1998** [comment]
ok！竟然直接有action

**Comment by tyn1998** [comment]
Chrome webstore中已经发布，但是由于IPC视图的完成（#1），需要在devconsole中更新插件的包以及描述信息。

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/32434520/192230114-91e5876e-865a-4a08-877a-c3950766e7cb.png">
