### ISSUE TITLE
[Chore] remove "DevTools" from "OpenSumi DevTools" string

### ISSUE THREAD

**Issue by tyn1998** [opensumi/devtools#7]
![image](https://user-images.githubusercontent.com/32434520/187063488-71f30413-1afa-42b8-89ae-7680f6617715.png)

**Comment by zhicheng-ning** [comment]
Hi,@tyn1998. I'd like to try to solve it~

**Comment by tyn1998** [comment]
Hi @zhicheng-ning, the issue will be assigned to you!
